package server

import (
	"strings"
	"testing"
)

func TestDashboardIncludesGraphPotentialControls(t *testing.T) {
	required := []string{
		`<option value="TASK_FOCUS">Task Focus</option>`,
		`<option value="CONTROL">Control View</option>`,
		`<option value="MEMORY_OVERLAY">Memory Overlay</option>`,
		`<option value="MEMORY_ATLAS">Memory Atlas</option>`,
		`id="graph-back-to-system"`,
		`id="graph-focus-meta"`,
		`id="graph-task-focus-picker-wrap"`,
		`id="graph-task-focus-select"`,
		`id="graph-control-focus-picker-wrap"`,
		`id="graph-control-focus-select"`,
		`id="graph-memory-atlas-controls-wrap"`,
		`id="graph-memory-atlas-query"`,
		`id="graph-memory-atlas-layer"`,
		`id="graph-memory-atlas-lifecycle"`,
		`id="graph-memory-atlas-origin"`,
		`id="graph-memory-atlas-epistemic"`,
		`id="graph-memory-atlas-depth"`,
		`id="graph-memory-atlas-canonical"`,
		`id="graph-memory-atlas-archived"`,
		`id="graph-memory-atlas-anchors"`,
		`id="graph-memory-atlas-lens-bar"`,
		`id="graph-memory-atlas-nav"`,
		`id="graph-memory-atlas-history"`,
		`id="graph-atlas-back-btn"`,
		`id="graph-atlas-overview-btn"`,
		`id="graph-toggle-affinity"`,
		`id="graph-affinity-threshold"`,
		`id="graph-affinity-threshold-val"`,
		"Potential Threshold",
		"Legend",
		"Agent fit",
		"Task surface",
		"Cluster pressure",
		"function graphEnterTaskFocus(taskID)",
		"function graphEnterControlFocus(clusterID)",
		"function graphShowControlOverview()",
		"function graphReturnToSystem()",
		"function handleGraphModeChange()",
		"function updateGraphTaskFocusOptions()",
		"function updateGraphControlFocusOptions()",
		"function handleGraphTaskFocusSelection()",
		"function handleGraphControlFocusSelection()",
		"function graphHumanizeProtoClusterID(clusterID, maxDetail)",
		"function graphControlClusterDisplayLabel(cluster)",
		"function graphControlClusterByID(clusterID)",
		"function graphNodeNeighborTypeCounts(nodeID)",
		"function graphControlClusterScopeSummary(clusterID)",
		"function graphMemoryOverlayCounts()",
		"function graphIsMemoryAtlasMode()",
		"function graphMemoryAtlasQuery()",
		"function graphMemoryAtlasLifecycle()",
		"function graphMemoryAtlasOriginKind()",
		"function graphMemoryAtlasEpistemicStatus()",
		"function graphMemoryAtlasCanonicalOnly()",
		"function graphMemoryAtlasIncludeArchived()",
		"function graphRenderMemoryAtlasHistory()",
		"function graphGoBackMemoryAtlasFocus()",
		"function graphApplyMemoryAtlasLens(lens)",
		"function handleGraphMemoryAtlasSearch()",
		"function graphEnterMemoryAtlasFocus(memoryID, options)",
		"function graphShowMemoryAtlasOverview()",
		"function showMemoryGraphNodeDetail(memoryId)",
		"Select task...",
		"All clusters",
		"Proto-Cluster ID:",
		"Cluster Pressure:",
		"Neighborhood:",
		"cluster-centered pressure map",
		"Focus Task Graph",
		"Focus Control Graph",
		"Open Memory Node",
		"Open Agent",
		"Center Here",
		"Expand Neighborhood",
		"Show Atlas Overview",
		"Memory overlay: canonical memory attached to active tasks, sessions, and agents",
		"Memory atlas overview: budgeted canonical memory map",
		"Search Atlas",
		"Everything",
		"Disputed",
		"Canonical",
		"Derived",
		"Back to Previous Focus",
		"Show Anchors",
		"Show All Clusters",
		"Open Control Scaffold",
		"Back to System",
		"function graphAffinityThreshold()",
		"function graphUpdateAffinityThresholdLabel()",
		"function graphSetHoverNode(node)",
		"function graphCurrentHoverNodeID()",
		"function graphSetDragHoverNode(node)",
		"function graphClearHoverState()",
		"function graphHoverHighlightsLink(link)",
		"function graphHoverHasAffinityFocus()",
		"function graphHoverDistanceForNode(node)",
		"function graphHoverDistanceForLink(link)",
		"function graphHoverNodeFalloff(node)",
		"function graphHoverLinkFalloff(link)",
		".onNodeDrag(function(node) {",
		".onNodeDragEnd(function() {",
		"drag focus",
		"function graphRecomputeBlockerState()",
		"function graphNodeIsBlockingAction(node)",
		"function graphNodeIsBlocked(node)",
		"function updateGraphVisibility()",
		"hover focus",
		"blocked_by_action",
		"workspace.memory.graph.atlas",
	}
	for _, needle := range required {
		if !strings.Contains(dashboardHTML, needle) {
			t.Fatalf("dashboard graph potential controls are missing %s", needle)
		}
	}
	forbidden := []string{
		`_graphRequestedFocusID || (_graphFocusNode && _graphFocusNode.type === 'task' ? graphNodeRefID(_graphFocusNode) : '')`,
		`_graphRequestedFocusID || (_graphFocusNode && _graphFocusNode.type === 'proto_cluster' ? graphNodeRefID(_graphFocusNode) : '')`,
		`_graphRequestedFocusID || (_graphFocusNode && _graphFocusNode.type === 'memory_node' ? graphNodeRefID(_graphFocusNode) : '')`,
	}
	for _, needle := range forbidden {
		if strings.Contains(dashboardHTML, needle) {
			t.Fatalf("dashboard still allows implicit graph focus fallback via %s", needle)
		}
	}
}
